[package]
name = "advent_of_code"
version = "0.0.1"

[[bin]]
name = "day-01"

[[bin]]
name = "day-02"

[[bin]]
name = "day-03"

[[bin]]
name = "day-04"

[[bin]]
name = "day-05"

[[bin]]
name = "day-06"

[[bin]]
name = "day-07"